"""initial_tables

Revision ID: 4dd2f926a659
Revises: 
Create Date: 2026-07-17 23:12:20.765005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd2f926a659'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(), nullable=False),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_logs_id'), 'mcp_logs', ['id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fuel', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('mission', sa.String(length=100), nullable=False),
    sa.Column('tle', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id')
    )
    op.create_index(op.f('ix_satellites_id'), 'satellites', ['id'], unique=False)
    op.create_table('simulation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('collision_probability', sa.Float(), nullable=False),
    sa.Column('risk_prediction', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id')
    )
    op.create_index(op.f('ix_simulation_sessions_id'), 'simulation_sessions', ['id'], unique=False)
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_id'), 'weather_cache', ['id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_table('negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('final_decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiations_id'), 'negotiations', ['id'], unique=False)
    op.create_table('negotiation_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('proposer', sa.String(), nullable=False),
    sa.Column('maneuver', sa.String(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_steps_id'), 'negotiation_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_steps_id'), table_name='negotiation_steps')
    op.drop_table('negotiation_steps')
    op.drop_index(op.f('ix_negotiations_id'), table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('ix_weather_cache_id'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_simulation_sessions_id'), table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    op.drop_index(op.f('ix_satellites_id'), table_name='satellites')
    op.drop_table('satellites')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_mcp_logs_id'), table_name='mcp_logs')
    op.drop_table('mcp_logs')
    # ### end Alembic commands ###
